global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nautilus-job'
    static_configs:
      - targets: ['host.docker.internal:12911']
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']